name: Build Releases JSON

on:
  schedule:
    - cron: '*/15 * * * *' # run every 15 minutes
  workflow_dispatch:
    inputs:
      verbose:
        description: "Enable detailed logging output"
        required: false
        default: "false"

permissions:
  contents: write # allow pushing commits

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install axios minimatch

      - name: Run generator
        id: generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          VERBOSE: ${{ github.event.inputs.verbose }}
        run: |
          echo "🔧 Running generateReleases.js (trigger: $GITHUB_EVENT_NAME, verbose: $VERBOSE)"
          node scripts/generateReleases.js

          # Count number of errors (lines starting with dash in ERRORS.md)
          ERRORS_COUNT=$(grep -c '^-' ERRORS.md || true)
          echo "errors_count=$ERRORS_COUNT" >> $GITHUB_OUTPUT

          # Extract first 5 error lines for preview
          PREVIEW=$(grep '^-' ERRORS.md | head -n 5 || true)

          # Encode for GITHUB_OUTPUT (required)
          ENCODED_PREVIEW="${PREVIEW//'%'/'%25'}"
          ENCODED_PREVIEW="${ENCODED_PREVIEW//$'\n'/'%0A'}"
          ENCODED_PREVIEW="${ENCODED_PREVIEW//$'\r'/'%0D'}"
          echo "error_preview=$ENCODED_PREVIEW" >> $GITHUB_OUTPUT

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add releases.json ERRORS.md
          git diff --cached --quiet || git commit -m "Update releases.json and ERRORS.md [skip ci]"
          git push

      - name: Upload ERRORS.md as artifact
        uses: actions/upload-artifact@v4
        with:
          name: error-report
          path: ERRORS.md
          if-no-files-found: warn
          retention-days: 14

      - name: Print summary
        run: |
          echo "## 🧩 Release Aggregation Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Trigger: \`${{ github.event_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Total errors or warnings: **${{ steps.generator.outputs.errors_count }}**" >> $GITHUB_STEP_SUMMARY
          echo "- Files generated: \`releases.json\`, \`ERRORS.md\`" >> $GITHUB_STEP_SUMMARY
          echo "- Error report attached as an artifact named 'error-report'." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🪵 Error Preview (first 5 entries)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.generator.outputs.errors_count }}" -eq 0 ]; then
            echo "✅ No errors or warnings this run!" >> $GITHUB_STEP_SUMMARY
          else
            # Use actual newlines for step summary
            grep '^-' ERRORS.md | head -n 5 >> $GITHUB_STEP_SUMMARY
            if [ "${{ steps.generator.outputs.errors_count }}" -gt 5 ]; then
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "_...and more. See full ERRORS.md artifact for details._" >> $GITHUB_STEP_SUMMARY
            fi
          fi
